import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tablerRoot = resolve(packageRoot, 'node_modules/@tabler/icons')
const generatedRoot = resolve(packageRoot, 'src/generated')

const packageJson = JSON.parse(await readFile(resolve(tablerRoot, 'package.json'), 'utf8'))
const manifest = JSON.parse(await readFile(resolve(packageRoot, 'icon-manifest.json'), 'utf8'))
const nodes = JSON.parse(await readFile(resolve(tablerRoot, 'tabler-nodes-outline.json'), 'utf8'))
const metadata = JSON.parse(await readFile(resolve(tablerRoot, 'icons.json'), 'utf8'))

if (packageJson.license !== 'MIT') {
  throw new Error(`Expected Tabler Icons to be MIT licensed, found ${packageJson.license}`)
}
if (packageJson.version !== '3.46.0') {
  throw new Error(`Expected pinned Tabler Icons 3.46.0, found ${packageJson.version}`)
}

const allNames = Object.keys(nodes)
  .filter((name) => !name.startsWith('brand-'))
  .sort()
const missing = manifest.essential.filter((name) => !nodes[name])
const missingConceptTargets = Object.values(manifest.concepts).filter((name) => !nodes[name])
const missingAliasTargets = Object.values(manifest.aliases).filter((name) => !nodes[name])
if (missing.length || missingConceptTargets.length || missingAliasTargets.length) {
  throw new Error(`Unknown Tabler icons: ${[
    ...missing,
    ...missingConceptTargets,
    ...missingAliasTargets,
  ].join(', ')}`)
}

const toIcons = (names) => Object.fromEntries(names.map((name) => [name, {
  elements: nodes[name],
}]))
const toCatalog = (names) => names.map((name) => ({
  name,
  tags: (metadata[name]?.tags ?? []).map(String),
  ...(metadata[name]?.category ? { category: metadata[name].category } : {}),
}))
const moduleHeader = '// Generated by scripts/generate-tabler.mjs. Do not edit by hand.\n'

await writeFile(resolve(generatedRoot, 'essential.ts'), `${moduleHeader}
import type { IconCatalogEntry, IconRegistry } from '../types'

export const TABLER_VERSION = '${packageJson.version}'
export const essentialIcons: IconRegistry = ${JSON.stringify(toIcons(manifest.essential))}
export const essentialCatalog: readonly IconCatalogEntry[] = ${JSON.stringify(toCatalog(manifest.essential))}
`)

await writeFile(resolve(generatedRoot, 'concepts.ts'), `${moduleHeader}
export const conceptIconMap = ${JSON.stringify(manifest.concepts, null, 2)} as const
export type IconConcept = keyof typeof conceptIconMap
`)

await writeFile(resolve(generatedRoot, 'aliases.ts'), `${moduleHeader}
export const iconAliasMap = ${JSON.stringify(manifest.aliases, null, 2)} as const
`)

await writeFile(resolve(generatedRoot, 'names.ts'), `${moduleHeader}
export const tablerIconNames: readonly string[] = ${JSON.stringify(allNames)}
`)

await writeFile(resolve(generatedRoot, 'tabler.ts'), `${moduleHeader}
import type { IconCatalogEntry, IconRegistry } from '../types'

export const TABLER_VERSION = '${packageJson.version}'
export const tablerIcons: IconRegistry = ${JSON.stringify(toIcons(allNames))}
export const tablerCatalog: readonly IconCatalogEntry[] = ${JSON.stringify(toCatalog(allNames))}
`)

console.log(`Generated ${manifest.essential.length} essential icons and ${allNames.length} non-brand Tabler icons.`)
